// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhx4rBW74KqGfNvE13_zdfPgucaZckbvI',
    appId: '1:400373791251:web:1ccc5e1ea7994a1510dde6',
    messagingSenderId: '400373791251',
    projectId: 'wedding-planner-71027',
    authDomain: 'wedding-planner-71027.firebaseapp.com',
    storageBucket: 'wedding-planner-71027.appspot.com',
    measurementId: 'G-G7J35LJJGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMwwbNTkJdf_up2jy-0obqMkRUXEbErbA',
    appId: '1:400373791251:android:5178ab8b4d06862310dde6',
    messagingSenderId: '400373791251',
    projectId: 'wedding-planner-71027',
    storageBucket: 'wedding-planner-71027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKw6Eb4km78-M9aI3XpLuBMD5MAml0_w',
    appId: '1:400373791251:ios:5d470c287b31a93610dde6',
    messagingSenderId: '400373791251',
    projectId: 'wedding-planner-71027',
    storageBucket: 'wedding-planner-71027.appspot.com',
    iosClientId: '400373791251-roihr6g8dj5i5j53r53n9bo84c7m76h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationPtoj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApKw6Eb4km78-M9aI3XpLuBMD5MAml0_w',
    appId: '1:400373791251:ios:5d470c287b31a93610dde6',
    messagingSenderId: '400373791251',
    projectId: 'wedding-planner-71027',
    storageBucket: 'wedding-planner-71027.appspot.com',
    iosClientId: '400373791251-roihr6g8dj5i5j53r53n9bo84c7m76h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationPtoj',
  );
}
